//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolucionBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cadenas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cadenas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvolucionBrowser.Cadenas", typeof(Cadenas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutA {
            get {
                return ResourceManager.GetString("aboutA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + favorites.
        /// </summary>
        public static string addFav {
            get {
                return ResourceManager.GetString("addFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy this App.
        /// </summary>
        public static string BuyApp {
            get {
                return ResourceManager.GetString("BuyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy the App.
        /// </summary>
        public static string BuyCaption {
            get {
                return ResourceManager.GetString("BuyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy the App for full experience and no ads. Do you want to buy the app?.
        /// </summary>
        public static string BuyMsg {
            get {
                return ResourceManager.GetString("BuyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Cookies.
        /// </summary>
        public static string cookies {
            get {
                return ResourceManager.GetString("cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome Mobile.
        /// </summary>
        public static string CrhomeMobile {
            get {
                return ResourceManager.GetString("CrhomeMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom User Agent.
        /// </summary>
        public static string CustomUserAgent {
            get {
                return ResourceManager.GetString("CustomUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer: Jose Mendez.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eMail: jmendez.blogspot@gmail.com.
        /// </summary>
        public static string eMail {
            get {
                return ResourceManager.GetString("eMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving image.
        /// </summary>
        public static string ErrorSavingImg {
            get {
                return ResourceManager.GetString("ErrorSavingImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want exit?.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string fav {
            get {
                return ResourceManager.GetString("fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to the developer.
        /// </summary>
        public static string Feedback1 {
            get {
                return ResourceManager.GetString("Feedback1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold the image to save it.
        /// </summary>
        public static string HoldMsg {
            get {
                return ResourceManager.GetString("HoldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer Mobile.
        /// </summary>
        public static string IEMobile {
            get {
                return ResourceManager.GetString("IEMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image is saved:.
        /// </summary>
        public static string ImgSaved {
            get {
                return ResourceManager.GetString("ImgSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Mobile.
        /// </summary>
        public static string MozillaMobile {
            get {
                return ResourceManager.GetString("MozillaMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name textbox can&apos;t be empty.
        /// </summary>
        public static string NoEmpty {
            get {
                return ResourceManager.GetString("NoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Apps.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other application from evolucion_phone.
        /// </summary>
        public static string Other1 {
            get {
                return ResourceManager.GetString("Other1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reate and Review.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the App in the Marketplace.
        /// </summary>
        public static string Rate1 {
            get {
                return ResourceManager.GetString("Rate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safari Mobile.
        /// </summary>
        public static string SafariMobile {
            get {
                return ResourceManager.GetString("SafariMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Imgs.
        /// </summary>
        public static string saveImg {
            get {
                return ResourceManager.GetString("saveImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string scode {
            get {
                return ResourceManager.GetString("scode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies:.
        /// </summary>
        public static string SeeCoockie {
            get {
                return ResourceManager.GetString("SeeCoockie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string SeeCookieName {
            get {
                return ResourceManager.GetString("SeeCookieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values: .
        /// </summary>
        public static string SeeCookieValues {
            get {
                return ResourceManager.GetString("SeeCookieValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Search Engine.
        /// </summary>
        public static string SelSearchEngine {
            get {
                return ResourceManager.GetString("SelSearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a User Agent:.
        /// </summary>
        public static string selUserAgent {
            get {
                return ResourceManager.GetString("selUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user agent.
        /// </summary>
        public static string setUA {
            get {
                return ResourceManager.GetString("setUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shake the phone to restore.
        /// </summary>
        public static string Shake {
            get {
                return ResourceManager.GetString("Shake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string Tap {
            get {
                return ResourceManager.GetString("Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
